version: '3'

volumes:
  venv:

services:
  bot:
    build: ./bot
    image: mkizka/discord-bot-python-runner
    env_file: .env
    volumes:
      - ./bot:/code
      - venv:/code/.venv
      - /var/run/docker.sock:/var/run/docker.sock
